project: 
   type: website
   output-dir: docs
include-in-header: analytics.html

website:
  title: "R@URBAN"
  navbar:
    pinned: true
    search: true
    left:
      - text: HOME
        file: index.qmd
      - text: INTRO TO R
        file: intro-to-r.html
      - text: DATA VIZ
        file: graphics-guide.html
      - text: MAPPING
        file: mapping.html
      - text: GETTING DATA
        file: getting-data.html    
      - text: OPTIMIZATION
        file: optimization.html
      - text: RESOURCES
        file: resources.html   

format:
  html:
    css: styles.css
    toc: true



